create table if not exists meeting_room (
    id bigint generated by default as identity,
    name varchar(255),
    size integer not null,
    primary key (id)
);

create table if not exists reservation (
    id bigint generated by default as identity,
    end_time timestamp,
    meeting_room_id bigint,
    start_time timestamp,
    user_id bigint,
    primary key (id)
);

create table if not exists `user` (
    id bigint generated by default as identity,
    dept varchar(255),
    name varchar(255),
    primary key (id)
);